language: c

env:
  global:
    - LUAROCKS=2.2.0-rc1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    # luajit fails on functional tests for complex reasons
    # disabling it for now
    # - LUA=luajit    

before_install:
  - bash .travis/setup_lua.sh

script: 
  - lua run_unit_tests.lua
  - lua run_functional_tests.lua

notifications:
  email:
    on_success: change
    on_failure: always
